### ISSUE TITLE
Subscription

### ISSUE THREAD

**Issue by peymanebrahimi** [fiyazbinhasan/GraphQLCore#4]
Hi thanks for wonderful series.
Would you please provide subscription section into these articles?

**Comment by fiyazbinhasan** [comment]
you mean graphql subscription? http://facebook.github.io/graphql/June2018/#sec-Subscription

**Comment by peymanebrahimi** [comment]
for this series of article
http://fiyazhasan.me/graphql-with-asp-net-core-part-x-data-loader-series-finale/
how to handle event stream for scoped dbContext?

**Comment by fiyazbinhasan** [comment]
Closing this as it's a feature request. For more info on this, please take a look at, https://graphql-dotnet.github.io/docs/getting-started/subscriptions
