### ISSUE TITLE
Link to graphql dotnet broken

### ISSUE THREAD

**Issue by pkellner** [fiyazbinhasan/GraphQLCore#6]
Link at bottom of this page:

https://github.com/fiyazbinhasan/GraphQLCore/tree/Part_X_DataLoader

is currently:  https://graphql-dotnet.github.io/dataloader/
should be:  https://graphql-dotnet.github.io/docs/guides/dataloader/

**Comment by fiyazbinhasan** [comment]
Thanks, @pkellner. Fixed! :)
